In [ ]:
import numpy as np

In [ ]:
 X = [8.4,10.2,16.5,21.7,9.4,8.3,11.5,18.4,16.7,19.3,28.4,4.7,12.3],


In [ ]:
X2 = np.square(X)

In [ ]:
X2

array([[ 70.56, 104.04, 272.25, 470.89,  88.36,  68.89, 132.25, 338.56,
        278.89, 372.49, 806.56,  22.09, 151.29]])

In [ ]:
Y = [35.9,31.8,24.7,25.2,36.8,35.8,33.4,25.4,31.4,27.4,15.8,31.5,28.9]

In [ ]:
Y2 = np.square(Y)

In [ ]:
Y2

array([1288.81, 1011.24,  610.09,  635.04, 1354.24, 1281.64, 1115.56,
        645.16,  985.96,  750.76,  249.64,  992.25,  835.21])

In [ ]:
np.sum(X)

185.8

In [ ]:
np.sum(Y)

383.99999999999994

In [ ]:
np.sum(X2)

3177.1200000000003

In [ ]:
np.sum(Y2)

11755.599999999999

In [ ]:
x_arr = np.array(X)
y_arr = np.array(Y)

sum_xy = (x_arr * y_arr)

In [ ]:
sum_xy

array([[301.56, 324.36, 407.55, 546.84, 345.92, 297.14, 384.1 , 467.36,
        524.38, 528.82, 448.72, 148.05, 355.47]])

In [ ]:
np.sum(sum_xy)

5080.27

In [ ]:
ybar = np.mean(Y)
print(ybar)

29.538461538461533


In [ ]:
num = np.sum((X - np.mean(X)) * (Y -np.mean(Y)))
den = np.sum((X-np.mean(X)) ** 2)

In [ ]:
b1 = num/den

In [ ]:
b1

-0.782149029925143

In [ ]:
bo = np.mean(Y) - b1* np.mean(X)
bo

40.717176135391654