In [1]:
import numpy as np

# Creating Array From Python List

In [2]:
np.array([1,8,6,9,45])

array([ 1,  8,  6,  9, 45])

In [4]:
np.array([1,8,6,9,45], dtype="float32")

array([ 1.,  8.,  6.,  9., 45.], dtype=float32)

In [5]:
# nested list result in multidimensional array
x = np.array([range(i, i+3) for i in [2,4,6]])
x

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

# Creating array from scratch

In [6]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones((3,5),dtype="float")

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
# Create a 3x5 array filled with 3.1415
np.full((3, 5), 3.1415)

array([[3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
       [3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
       [3.1415, 3.1415, 3.1415, 3.1415, 3.1415]])

In [10]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.89464974, 0.0652501 , 0.92721491],
       [0.85845776, 0.73696951, 0.2753517 ],
       [0.19849999, 0.7215271 , 0.36450622]])

In [13]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.75934308,  0.37242794, -0.26654581],
       [ 0.16797175,  0.14883719,  0.54095268],
       [ 1.68106954, -0.73419768, -1.4694768 ]])

In [14]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[3, 0, 8],
       [3, 0, 0],
       [8, 5, 8]])

In [15]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

# Numpy Data Types
- Data type	->  Description
- bool_	-> Boolean (True or False) stored as a byte
- int_	-> Default integer type (same as C long; normally either int64 or int32)
- intc	-> Identical to C int (normally int32 or int64)
- intp	-> Integer used for indexing (same as C ssize_t; normally either int32 or int64)
- int8	-> Byte (-128 to 127)
- int16	-> Integer (-32768 to 32767)
- int32	-> Integer (-2147483648 to 2147483647)
- int64	-> Integer (-9223372036854775808 to 9223372036854775807)
- uint8	-> Unsigned integer (0 to 255)
- uint16	-> Unsigned integer (0 to 65535)
- uint32	-> Unsigned integer (0 to 4294967295)
- uint64	-> Unsigned integer (0 to 18446744073709551615)
- float_	-> Shorthand for float64.
- float16	-> Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
- float32	-> Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
- float64	-> Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
- complex_ ->	Shorthand for complex128.
- complex64 ->	Complex number, represented by two 32-bit floats
- complex128	-> Complex number, represented by two 64-bit floats

In [17]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

# Basics Of Numpy Array

In [18]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [19]:
x1

array([6, 1, 2, 7, 1, 4])

In [20]:
x3.ndim

3

In [21]:
x3.shape

(3, 4, 5)

In [23]:
x3.itemsize   # Other attributes include itemsize, which lists the size (in bytes) of each array element

4

In [24]:
x3.nbytes    # nbytes = total size (in bytes) of the array

240

In [25]:
x1[-1]

4

In [26]:
x2

array([[9, 2, 5, 5],
       [3, 2, 4, 1],
       [3, 3, 9, 9]])

In [27]:
x2[2,-1]

9

In [28]:
x2[0, 0] = 12
x2

array([[12,  2,  5,  5],
       [ 3,  2,  4,  1],
       [ 3,  3,  9,  9]])

# Array Slicing: Accessing Subarrays

x[start:stop:step]
If any of these are unspecified, they default to the values start=0, stop=size of dimension, step=1. We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### ONE DIMENSIONAL SUBARRAY

In [29]:
x = np.arange(10)

In [30]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
x[:5] # first five elements

array([0, 1, 2, 3, 4])

In [32]:
x[5:] # elements after index 5

array([5, 6, 7, 8, 9])

In [33]:
x[4:7] # middle subarray

array([4, 5, 6])

In [34]:
x[::2] #every other element

array([0, 2, 4, 6, 8])

In [35]:
x[1::2] # every other element, starting at index 1

array([1, 3, 5, 7, 9])

A potentially confusing case is when the step value is negative. In this case, the defaults for start and stop are swapped. This becomes a convenient way to reverse an array:

In [36]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [37]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

# Multi-dimensional Sub-arrays

In [38]:
x2

array([[12,  2,  5,  5],
       [ 3,  2,  4,  1],
       [ 3,  3,  9,  9]])

In [39]:
x2[:2, :3]  # two rows, three columns

array([[12,  2,  5],
       [ 3,  2,  4]])

In [40]:
x2[:3, ::2]  # all rows, every other column

array([[12,  5],
       [ 3,  4],
       [ 3,  9]])

In [41]:
x2[:3, ::2]  # all rows, every other column

array([[12,  5],
       [ 3,  4],
       [ 3,  9]])

In [42]:
x2[::-1, ::-1]  # subarray dimensions can even be reversed together

array([[ 9,  9,  3,  3],
       [ 1,  4,  2,  3],
       [ 5,  5,  2, 12]])

In [43]:
print(x2[:, 0])  # first column of x2

[12  3  3]


In [44]:
print(x2[0, :])  # first row of x2

[12  2  5  5]


# Views and Copies

In [45]:
arr = np.arange(12)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [47]:
arr[5:8]

array([5, 6, 7])

In [50]:
l = [x for x in range(12)]

In [51]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [52]:
l[5:8]

[5, 6, 7]

In [53]:
arr[5:8] = 12 # all three values are overwritten (would give error on a list)

In [54]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9, 10, 11])

In [55]:
l[5:8] = 12

TypeError: can only assign an iterable

In [56]:
arr_view =  arr[5:8]

In [58]:
arr_view[:] = 13 # modifies arr_view

In [59]:
arr

array([ 0,  1,  2,  3,  4, 13, 13, 13,  8,  9, 10, 11])

In [60]:
arr_view

array([13, 13, 13])

In [61]:
arr_copy = arr[5:8].copy() # makes a copy instead

In [62]:
arr_copy[:] = 14

In [63]:
arr_copy

array([14, 14, 14])

# Reshaping of Arrays

Another useful type of operation is reshaping of arrays. The most flexible way of doing this is with the reshape method. For example, if you want to put the numbers 1 through 9 in a 3×3 grid, you can do the following

In [64]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size of the initial array must match the size of the reshaped array. Where possible, the reshape method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix. This can be done with the reshape method, or more easily done by making use of the newaxis keyword within a slice operation

In [65]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [66]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [67]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [68]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

# Array Concatenation and Splitting

In [69]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [70]:
# You can also concatenate more than two arrays at once:

z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [71]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [72]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [73]:
np.concatenate([grid, grid], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

For working with arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack) and np.hstack (horizontal stack) functions:

In [74]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [75]:
np.vstack([grid,x])

array([[9, 8, 7],
       [6, 5, 4],
       [1, 2, 3]])

In [76]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

Similary, np.dstack will stack arrays along the third axis.

# Spliting of arrays

The opposite of concatenation is splitting, which is implemented by the functions np.split, np.hsplit, and np.vsplit. For each of these, we can pass a list of indices giving the split points

In [77]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [79]:
grid = np.arange(16).reshape((4,4))

In [80]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [81]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [82]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


Similarly, np.dsplit will split arrays along the third axis.
